author: zhuowei
database: false
description: RecordRepeatPlugin
main: net.zhuoweizhang.recordrepeat.RecordRepeatPlugin
name: RecordRepeatPlugin
startup: postworld
version: '1.1'
commands:
   rr:
      description: RecordRepeat Help
      usage: To use RecordRepeat type /<command> help
   recordrepeat:
      description: RecordRepeat Help
      usage: To use RecordRepeat type /<command> help
permissions:
    recordrepeat.use:
        description: Use RecordRepeat
        default: true